### ISSUE TITLE
Build Failed 

### ISSUE THREAD

**Issue by Vigneshbosch** [I809764/smallEx1#2]
Hi , 

I am facing the below issue while trying to build the application. Please let me know if there are any modification required in the .yaml file.

14:18:49 (DIBuild) >  [INFO] Injecting source code into builder...>  [INFO] Source code injection finished>  [INFO] ------------------------------------------------------------------------>  No package.json file detected. Build process will use an automatically generated one.>  added 12 packages from 29 contributors in 2.185s[INFO] Processing module web[ERROR] Invalid mta.yaml. Make sure that the declared type html5 of module web matches the actual module type blank.
14:18:50 (Builder) Build of /smallEx1 failed.

**Comment by I809764** [comment]
Were are you building this at?  Inside the SAP Web IDE for SAP HANA? Did you clone the project or recreate it by hand? I'm guessing you are either trying to build in a tool other than the SAP Web IDE for SAP HANA (maybe the old SAP Web IDE instead) or you made some error typing in the mta.yaml file.

**Comment by austinkloske22** [comment]
I got the same issue when cloning a repository between Web IDE for HANA and Full Stack. After adjusting the web/.che/project.jason I was able to build the web module.

In my case,
Web IDE for HANA "type": "sap.html5"
"Web IDE Full Stack "type": "com.sap.hcp.html5"
